"""empty message

Revision ID: 915aaf730a26
Revises: 5b1c556bd503
Create Date: 2024-09-02 16:38:03.612696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '915aaf730a26'
down_revision = '5b1c556bd503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
